class AddCreditCardLocators:
    EL_HEADER = '//XCUIElementTypeOther[@name="Add credit card"]'
    BTN_BACK = '//XCUIElementTypeOther[@name="Add credit card"]/following-sibling::XCUIElementTypeButton[1]'
    TXT_CARDHOLDER_LABEL = '//XCUIElementTypeStaticText[@name="Cardholder name"]'
    INPUT_CARDHOLDER_NAME = '//XCUIElementTypeTextField[@name="Enter name"]'
    TXT_CARD_NUMBER_LABEL = '//XCUIElementTypeStaticText[@name="Card number"]'
    EL_CARD_NUMBER_FIELD = '//XCUIElementTypeOther[starts-with(@name,"0000")]'
    INPUT_CARD_NUMBER = '//XCUIElementTypeOther[starts-with(@name,"0000")]/following-sibling::XCUIElementTypeTextField[1]'
    IMG_CARD_BRAND = '//XCUIElementTypeOther[starts-with(@name,"0000")]/following-sibling::XCUIElementTypeImage[1]'
    TXT_EXPIRY_LABEL = '//XCUIElementTypeStaticText[@name="Expiry date"]'
    INPUT_EXPIRY_DATE = '//XCUIElementTypeTextField[@name="MM / YY"]'
    TXT_CVV_LABEL = '//XCUIElementTypeStaticText[@name="CVV"]'
    INPUT_CVV = '//XCUIElementTypeTextField[@name="123"]'
    EL_PRIMARY_METHOD = '//XCUIElementTypeOther[@name="Set as primary method"]'
    SWITCH_PRIMARY_METHOD = '//XCUIElementTypeOther[@name="Set as primary method"]/following-sibling::XCUIElementTypeSwitch[1]'
    TXT_CHARGE_NOTE = '//XCUIElementTypeStaticText[starts-with(@name,"Your card may be charged")]'
    TXT_TERMS_NOTE = '//XCUIElementTypeStaticText[starts-with(@name,"By adding your debit")]'
    LINK_TERMS = '//XCUIElementTypeLink[starts-with(@name,"Terms")]'
    BTN_SAVE_CREDIT_CARD = '//XCUIElementTypeButton[@name="Save credit card"]'
    TXT_SCRIM = '//XCUIElementTypeStaticText[@name="Scrim"]'
