class BookingDetailsLocators:
    EL_TITLE = '//XCUIElementTypeOther[@name="Booking details"]'
    BTN_BACK = '//XCUIElementTypeOther[@name="Booking details"]/preceding-sibling::XCUIElementTypeButton[1]'
    BTN_MORE = '//XCUIElementTypeOther[@name="Booking details"]/following-sibling::XCUIElementTypeButton[1]'
    TXT_SUMMARY_TITLE = '//XCUIElementTypeStaticText[@name="Booking summary"]'
    TXT_STATUS = '//XCUIElementTypeStaticText[@name="{}"]'
    TXT_STATUS_UPCOMING = '//XCUIElementTypeStaticText[@name="UPCOMING"]'
    TXT_STATUS_RESCHEDULED = '//XCUIElementTypeStaticText[@name="RESCHEDULED"]'
    TXT_BOOKING_ID = '//XCUIElementTypeStaticText[starts-with(@name,"Booking #")]'
    TXT_FIELD = '//XCUIElementTypeStaticText[@name="{}"]'
    BTN_SEE_BREAKDOWN = '//XCUIElementTypeButton[@name="See complete breakdown"]'
    TXT_PAYMENT_SUMMARY = '//XCUIElementTypeStaticText[@name="Payment summary"]'
    IMG_TOTAL_PAYMENT = '//XCUIElementTypeImage[starts-with(@name,"Total payment")]'
    BTN_SEE_RECEIPT = '//XCUIElementTypeButton[@name="See receipt"]'
    BTN_SEE_DETAILS = '//XCUIElementTypeButton[@name="See details"]'
    TXT_RESCHEDULE_SUMMARY = '//XCUIElementTypeStaticText[@name="Reschedule summary"]'
    IMG_DATE_CHANGE = '//XCUIElementTypeImage[starts-with(@name,"Original date")]'
    TXT_HISTORY = '//XCUIElementTypeStaticText[@name="History"]'
    EL_HISTORY_ENTRY = '//XCUIElementTypeOther[starts-with(@name,"{}")]'
    IMG_HISTORY_ENTRY = '//XCUIElementTypeImage[starts-with(@name,"{}")]'
    LIST_CONTENT = '//XCUIElementTypeScrollView'
