class ConfirmRescheduleLocators:
    EL_TITLE = '//XCUIElementTypeOther[@name="Confirm reschedule"]'
    BTN_BACK = '//XCUIElementTypeOther[@name="Confirm reschedule"]/preceding-sibling::XCUIElementTypeButton[1]'
    TXT_VENUE = '//XCUIElementTypeStaticText[contains(@name,"Driving Range")]'
    TXT_FIELD = '//XCUIElementTypeStaticText[@name="{}"]'
    IMG_DATE_CHANGE = '//XCUIElementTypeImage[starts-with(@name,"Original date")]'
    TXT_REASON_TITLE = '//XCUIElementTypeStaticText[@name="Reschedule reason"]'
    BTN_REASON = '//XCUIElementTypeButton[@name="{}"]'
    BTN_REASON_WRONG_DATE = '//XCUIElementTypeButton[@name="Wrong date or time booked"]'
    BTN_REASON_BAD_WEATHER = '//XCUIElementTypeButton[@name="Bad weather"]'
    BTN_REASON_TRAFFIC = '//XCUIElementTypeButton[@name="Traffic jam"]'
    BTN_REASON_EMERGENCY = '//XCUIElementTypeButton[@name="Emergency situation"]'
    BTN_REASON_OTHER = '//XCUIElementTypeButton[@name="Other reasons"]'
    TXT_RESCHEDULE_FEE = '//XCUIElementTypeStaticText[@name="Reschedule fee"]'
    IMG_PRICE_DIFFERENCE = '//XCUIElementTypeImage[@name="Price difference"]'
    IMG_PAYMENT_METHOD = '//XCUIElementTypeImage[@name="{}"]'
    TXT_PAYMENT_DETAILS = '//XCUIElementTypeStaticText[@name="Payment details"]'
    BTN_CONFIRM_AND_PAY = '//XCUIElementTypeButton[starts-with(@name,"Confirm reschedule &")]'
