class PurchaseAuthenticationLocators:
    EL_HEADER_VISA = '//XCUIElementTypeOther[@name="VISA"]'
    BTN_BACK = '//XCUIElementTypeOther[@name="VISA"]/preceding-sibling::XCUIElementTypeButton[1]'
    BTN_CLOSE = '//XCUIElementTypeOther[@name="VISA"]/following-sibling::XCUIElementTypeButton[1]'
    NAV_XENDIT_AUTHENTICATION = '//XCUIElementTypeNavigationBar[@name="Xendit.AuthenticationWebView"]'
    BTN_NAV_CANCEL = '//XCUIElementTypeNavigationBar[@name="Xendit.AuthenticationWebView"]/XCUIElementTypeButton[@name="Cancel"]'
    EL_CHALLENGE_IFRAME = '//XCUIElementTypeOther[@name="challenge-iframe"]'
    EL_STEP_UP_IFRAME = '//XCUIElementTypeOther[contains(@name,"cardinal-stepUpIframe")]'
    EL_BANNER = '//XCUIElementTypeOther[@name="banner"]'
    TXT_TITLE = '//XCUIElementTypeStaticText[@name="Purchase Authentication"]'
    TXT_OTP_MESSAGE = '//XCUIElementTypeStaticText[starts-with(@name,"We have sent you a text message")]'
    TXT_ENTER_CODE_LABEL = '//XCUIElementTypeStaticText[@name="Enter your code below"]'
    INPUT_OTP_CODE = '//XCUIElementTypeButton[@name="SUBMIT"]/preceding-sibling::XCUIElementTypeTextField[1]'
    BTN_SUBMIT = '//XCUIElementTypeButton[@name="SUBMIT"]'
    BTN_RESEND_CODE = '//XCUIElementTypeButton[@name="RESEND CODE"]'
    BTN_CANCEL = '//XCUIElementTypeButton[@name="CANCEL"]'
    EL_NEED_HELP_SECTION = '//XCUIElementTypeOther[starts-with(@name,"Need some help?")]'
    TXT_NEED_HELP = '//XCUIElementTypeStaticText[@name="Need some help?"]'
    TXT_HELP_CONTENT = '//XCUIElementTypeStaticText[@name="Help content will be displayed here."]'
    EL_LEARN_MORE_SECTION = '//XCUIElementTypeOther[starts-with(@name,"Learn more about authentication")]'
    TXT_LEARN_MORE = '//XCUIElementTypeStaticText[@name="Learn more about authentication"]'
    TXT_AUTHENTICATION_INFO = '//XCUIElementTypeStaticText[@name="Authentication information will be displayed here."]'
