class RescheduleBookingLocators:
    EL_TITLE = '//XCUIElementTypeOther[@name="Reschedule booking"]'
    BTN_BACK = '//XCUIElementTypeOther[@name="Reschedule booking"]/preceding-sibling::XCUIElementTypeButton[1]'
    TXT_SECTION_TITLE = '//XCUIElementTypeStaticText[starts-with(@name,"Select new date")]'
    TXT_FIELD = '//XCUIElementTypeStaticText[@name="{}"]'
    TXT_WEEK_RANGE = '//XCUIElementTypeStaticText[contains(@name," - ")]'
    BTN_PREV_WEEK = '//XCUIElementTypeStaticText[contains(@name," - ")]/preceding-sibling::XCUIElementTypeButton[1]'
    BTN_NEXT_WEEK = '//XCUIElementTypeStaticText[contains(@name," - ")]/following-sibling::XCUIElementTypeButton[1]'
    BTN_OPEN_CALENDAR = '//XCUIElementTypeStaticText[contains(@name," - ")]/following-sibling::XCUIElementTypeButton[2]'
    BTN_DAY = '//XCUIElementTypeButton[@name="{}"]'
    LIST_DAYS = '//XCUIElementTypeButton[string-length(@name)<3 and number(@name)=number(@name)]'
    TXT_TIME_SLOT = '//XCUIElementTypeStaticText[@name="{}"]'
    LIST_TIME_SLOTS = '//XCUIElementTypeStaticText[contains(@name,":00")]'
    BTN_CONFIRM_DATETIME = '//XCUIElementTypeButton[starts-with(@name,"Confirm new date")]'
