class EventAddPlayerLocators:
    EL_TITLE = '//XCUIElementTypeOther[@name="Add a player"]'
    BTN_CLOSE = '//XCUIElementTypeOther[@name="Add a player"]/following-sibling::XCUIElementTypeButton[1]'
    EL_TAB_ROW = '//XCUIElementTypeOther[starts-with(@name,"Tab 1 of 2")] | //XCUIElementTypeStaticText[starts-with(@name,"Tab 1 of 2")]'
    TAB_SEARCH_FRIEND = '//XCUIElementTypeStaticText[starts-with(@name,"Tab 1 of 2")]'
    TAB_ADD_MANUALLY = '//XCUIElementTypeStaticText[starts-with(@name,"Tab 2 of 2")]'
    INPUT_SEARCH = '//XCUIElementTypeTextField'
    BTN_CLEAR_SEARCH = '//XCUIElementTypeTextField/following-sibling::XCUIElementTypeImage[1]'
    TXT_SEARCH_HINT = '//XCUIElementTypeStaticText[starts-with(@name,"Search for your friend")]'
    TXT_RESULT_BY_TEXT = '//XCUIElementTypeStaticText[contains(@name,"{}")]'
    TXT_RESULT_COUNT = '//XCUIElementTypeStaticText[contains(@name,"search result(s) found")]'
    IMG_ADD_FROM_CONTACTS = '//XCUIElementTypeImage[@name="Add from contacts"]'
    INPUT_FIRST_NAME = '//XCUIElementTypeTextField[@name="* First name"]'
    INPUT_LAST_NAME = '//XCUIElementTypeTextField[@name="* Last name"]'
    INPUT_PHONE_NUMBER = '//XCUIElementTypeTextField[@name="* Phone number"]'
    INPUT_EMAIL = '//XCUIElementTypeTextField[@name="Email"]'
    EL_COUNTRY = '//XCUIElementTypeOther[@name="Country"]'
    TXT_EMAIL_NOTE = '//XCUIElementTypeStaticText[@name="Registration confirmation will be sent to this email"]'
    BTN_SAVE_PLAYER = '//XCUIElementTypeButton[@name="Save player"]'
    TXT_SCRIM = '//XCUIElementTypeStaticText[@name="Scrim"]'
