class EventDetailsLocators:
    EL_HEADER = '//XCUIElementTypeOther[@name="Event details"]'
    BTN_BACK = '//XCUIElementTypeOther[@name="Event details"]/preceding-sibling::XCUIElementTypeButton[1]'
    BTN_SHARE = '//XCUIElementTypeOther[@name="Event details"]/following-sibling::XCUIElementTypeButton[1]'
    EL_LEADERBOARD_BANNER = '//XCUIElementTypeOther[starts-with(@name,"See event")]'
    TXT_EVENT_NAME = '//XCUIElementTypeStaticText[@name="{}"]'
    EL_LOCATION = '//XCUIElementTypeOther[contains(@name,"km away")]'
    EL_CASHBACK_BANNER = '//XCUIElementTypeOther[starts-with(@name,"Earn up to")]'
    TXT_LABEL_BY_NAME = '//XCUIElementTypeStaticText[@name="{}"]'
    TXT_VALUE_BY_LABEL = '//XCUIElementTypeStaticText[@name="{}"]/following-sibling::XCUIElementTypeStaticText[1]'
    TXT_VENUE_VALUE = '//XCUIElementTypeStaticText[@name="Venue"]/following-sibling::XCUIElementTypeStaticText[1]'
    TXT_DATE_VALUE = '//XCUIElementTypeStaticText[@name="Date"]/following-sibling::XCUIElementTypeStaticText[1]'
    TXT_STARTING_TIME_VALUE = '//XCUIElementTypeStaticText[@name="Deadline"]/following-sibling::XCUIElementTypeStaticText[1]'
    TXT_DEADLINE_VALUE = '//XCUIElementTypeStaticText[@name="Deadline"]/following-sibling::XCUIElementTypeStaticText[2]'
    TXT_REGISTRATION_FEE_VALUE = '//XCUIElementTypeStaticText[@name="Registration fee"]/following-sibling::XCUIElementTypeStaticText[1]'
    BTN_SECURE_SLOT = '//XCUIElementTypeButton[@name="Secure your slot"]'
    IMG_EVENT_BANNER = '//XCUIElementTypeScrollView/following-sibling::XCUIElementTypeImage[1]'
    EL_SWING_PASS_BANNER = '//XCUIElementTypeOther[@name="This event is Swing Pass exclusive"]'
    EL_BANNER_BY_TEXT = '//XCUIElementTypeOther[starts-with(@name,"{}")]'
    TXT_SWING_PASS_ONLY = '//XCUIElementTypeStaticText[@name="For Swing Pass Only"]'
    TXT_EVENT_INFORMATION = '//XCUIElementTypeStaticText[@name="Event information & rundown"]'
    TXT_STARTING_FROM = '//XCUIElementTypeStaticText[starts-with(@name,"Starting from")]'
    TXT_STARTING_TIME_LABEL = '//XCUIElementTypeStaticText[@name="Starting time"]'
    TXT_DEADLINE_LABEL = '//XCUIElementTypeStaticText[@name="Deadline"]'
    TXT_VENUE_LABEL = '//XCUIElementTypeStaticText[@name="Venue"]'
    TXT_DATE_LABEL = '//XCUIElementTypeStaticText[@name="Date"]'
