class PlayerDetailsLocators:
    EL_TITLE = '//XCUIElementTypeOther[@name="Fill in details"]'
    BTN_CLOSE = '//XCUIElementTypeOther[@name="Fill in details"]/following-sibling::XCUIElementTypeButton[1]'
    TXT_PLAYER_NAME = '//XCUIElementTypeStaticText[@name="{}"]'
    TXT_ACCOUNT_TYPE = '//XCUIElementTypeStaticText[@name="Swing account"]'
    BTN_CHANGE_PLAYER = '//XCUIElementTypeButton[@name="Change player"]'
    BTN_REMOVE_PLAYER = '//XCUIElementTypeButton[@name="Remove player"]'
    EL_QUESTION_BY_TEXT = '//XCUIElementTypeOther[starts-with(@name,"{}")]'
    EL_QUESTION_GENDER = '//XCUIElementTypeOther[starts-with(@name,"What is your gender?")]'
    EL_QUESTION_EXPERIENCE = '//XCUIElementTypeOther[starts-with(@name,"How experienced are you in golf?")]'
    EL_QUESTION_BIRTHDAY = '//XCUIElementTypeOther[starts-with(@name,"When is your birthday?")]'
    EL_QUESTION_SHIRT_SIZE = '//XCUIElementTypeOther[@name="Select shirt size"]'
    EL_OPTION_BY_NAME = '//XCUIElementTypeOther[@name="{}"]'
    BTN_OPTION_BY_NAME = '//XCUIElementTypeOther[@name="{}"]/following-sibling::XCUIElementTypeButton[1]'
    IMG_HCP_FILE = '//XCUIElementTypeImage[starts-with(@name,"hcp file generator")]'
    BTN_DOWNLOAD_TEMPLATE = '//XCUIElementTypeButton[@name="Download template"]'
    BTN_UPLOAD_FILE = '//XCUIElementTypeButton[@name="Upload file here"]'
    BTN_SAVE_PLAYER_DETAILS = '//XCUIElementTypeButton[@name="Save player details"]'
    TXT_SCRIM = '//XCUIElementTypeStaticText[@name="Scrim"]'
