class RegistrationSuccessLocators:
    TXT_TITLE = '//XCUIElementTypeStaticText[@name="You’re confirmed!"]'
    TXT_SUBTITLE = '//XCUIElementTypeStaticText[@name="See you on the event"]'
    TXT_EVENT_NAME = '//XCUIElementTypeStaticText[@name="{}"]'
    TXT_REGISTRATION_CODE = '//XCUIElementTypeStaticText[starts-with(@name,"Registration #")]'
    TXT_VALUE_BY_LABEL = '//XCUIElementTypeStaticText[@name="{}"]/following-sibling::XCUIElementTypeStaticText[1]'
    TXT_LABEL_DATE = '//XCUIElementTypeStaticText[@name="Date"]'
    TXT_LABEL_STARTING_TIME = '//XCUIElementTypeStaticText[@name="Starting time"]'
    TXT_LABEL_VENUE = '//XCUIElementTypeStaticText[@name="Venue"]'
    TXT_LABEL_PLAYERS = '//XCUIElementTypeStaticText[@name="Players"]'
    TXT_LABEL_TOTAL = '//XCUIElementTypeStaticText[@name="Total"]'
    TXT_LABEL_PAYMENT_METHOD = '//XCUIElementTypeStaticText[@name="Payment method"]'
    TXT_EARNED_CREDITS_LABEL = '//XCUIElementTypeStaticText[@name="Swing Credits you earned"]'
    EL_EARNED_CREDITS = '//XCUIElementTypeOther[starts-with(@name,"+ ")]'
    TXT_CREDITS_NOTE = '//XCUIElementTypeStaticText[starts-with(@name,"Swing Credits will only be issued")]'
    BTN_FINISH = '//XCUIElementTypeButton[@name="Finish"]'
    BTN_SEE_REGISTRATION_DETAILS = '//XCUIElementTypeButton[@name="See registration details"]'
