class RegistrationSummaryLocators:
    EL_HEADER = '//XCUIElementTypeOther[@name="Registration summary"]'
    BTN_BACK = '//XCUIElementTypeOther[@name="Registration summary"]/preceding-sibling::XCUIElementTypeButton[1]'
    EL_LEADERBOARD_BANNER = '//XCUIElementTypeOther[starts-with(@name,"See event")]'
    TXT_EVENT_NAME = '//XCUIElementTypeStaticText[@name="{}"]'
    TXT_VALUE_BY_LABEL = '//XCUIElementTypeStaticText[@name="{}"]/following-sibling::XCUIElementTypeStaticText[1]'
    TXT_LABEL_DATE = '//XCUIElementTypeStaticText[@name="Date"]'
    TXT_LABEL_STARTING_TIME = '//XCUIElementTypeStaticText[@name="Starting time"]'
    TXT_LABEL_VENUE = '//XCUIElementTypeStaticText[@name="Venue"]'
    TXT_REGISTRATION_TYPE = '//XCUIElementTypeStaticText[@name="Standard registration"]'
    IMG_PLAYER_BY_NAME = '//XCUIElementTypeImage[contains(@name,"{}") and not(contains(@name,"Package"))]'
    LIST_PLAYERS = '//XCUIElementTypeImage[contains(@name,"Swing Pass member") or contains(@name,"Regular Swing player")]'
    EL_SEE_PLAYER_DETAILS = '//XCUIElementTypeOther[@name="See player details"]'
    TXT_PACKAGE_LINE = '//XCUIElementTypeStaticText[starts-with(@name,"Package")]'
    TXT_NOTES_TITLE = '//XCUIElementTypeStaticText[starts-with(@name,"Notes to")]'
    TXT_NOTES_VALUE = '//XCUIElementTypeStaticText[contains(@name,"reservation notes")]'
    TXT_TERMS_TITLE = '//XCUIElementTypeStaticText[@name="Terms & conditions"]'
    TXT_PRICE_DETAILS_TITLE = '//XCUIElementTypeStaticText[@name="Price details"]'
    IMG_PRICE_LINE_BY_PLAYER = '//XCUIElementTypeImage[starts-with(@name,"{}") and contains(@name,"Package")]'
    EL_PROCESSING_FEE = '//XCUIElementTypeOther[starts-with(@name,"Processing fee")]'
    TXT_TOTAL_PAYMENT = '//XCUIElementTypeStaticText[starts-with(@name,"Total payment")]'
