class RegistrationDetailsLocators:
    EL_HEADER = '//XCUIElementTypeOther[@name="Registration details"]'
    BTN_BACK = '//XCUIElementTypeOther[@name="Registration details"]/preceding-sibling::XCUIElementTypeButton[1]'
    BTN_MORE = '//XCUIElementTypeOther[@name="Registration details"]/following-sibling::XCUIElementTypeButton[1]'
    EL_LEADERBOARD_BANNER = '//XCUIElementTypeOther[starts-with(@name,"See event")]'
    TXT_QR_TITLE = '//XCUIElementTypeStaticText[@name="qr code"]'
    TXT_QR_CODE = '//XCUIElementTypeStaticText[@name="qr code"]/following-sibling::XCUIElementTypeStaticText[1]'
    TXT_QR_NOTE = '//XCUIElementTypeStaticText[starts-with(@name,"QR Code can only be scannable")]'
    TXT_SUMMARY_TITLE = '//XCUIElementTypeStaticText[@name="Registration summary"]'
    TXT_STATUS = '//XCUIElementTypeStaticText[@name="UPCOMING"]'
    TXT_STATUS_BY_NAME = '//XCUIElementTypeStaticText[@name="{}"]'
    TXT_REGISTRATION_CODE = '//XCUIElementTypeStaticText[starts-with(@name,"Registration #")]'
    TXT_VALUE_BY_LABEL = '//XCUIElementTypeStaticText[@name="{}"]/following-sibling::XCUIElementTypeStaticText[1]'
    TXT_LABEL_DATE = '//XCUIElementTypeStaticText[@name="Date"]'
    TXT_LABEL_STARTING_TIME = '//XCUIElementTypeStaticText[@name="Starting time"]'
    TXT_LABEL_VENUE = '//XCUIElementTypeStaticText[@name="Venue"]'
    BTN_SEE_BREAKDOWN = '//XCUIElementTypeButton[@name="See complete breakdown"]'
    TXT_FLIGHT_TITLE = '//XCUIElementTypeStaticText[@name="Flight arrangement"]'
    EL_FLIGHT_BY_NAME = '//XCUIElementTypeOther[@name="{}"]'
    LIST_UNASSIGNED_SLOTS = '//XCUIElementTypeImage[@name="Unassigned"]'
