class ActivityLocators:
    EL_TITLE = '//XCUIElementTypeOther[@name="Activity"]'
    BTN_BACK = '//XCUIElementTypeOther[@name="Activity"]/preceding-sibling::XCUIElementTypeButton[1]'
    BTN_NOTIFICATION = '//XCUIElementTypeOther[@name="Activity"]/following-sibling::XCUIElementTypeButton[1]'
    IMG_CATEGORY_TAB = '//XCUIElementTypeImage[contains(@name,"{}")]'
    IMG_TAB_DRIVING_RANGE = '//XCUIElementTypeImage[contains(@name,"Driving range")]'
    IMG_TAB_TEE_TIME = '//XCUIElementTypeImage[contains(@name,"Tee time")]'
    IMG_TAB_EVENT = '//XCUIElementTypeImage[contains(@name,"Event")]'
    IMG_TAB_MARKETPLACE = '//XCUIElementTypeImage[contains(@name,"Marketplace")]'
    LIST_BOOKING_CARDS = '//XCUIElementTypeImage[contains(@name," on ")]'
    CELL_BOOKING = '//XCUIElementTypeImage[contains(@name,"{}")]'
    TXT_STATUS = '//XCUIElementTypeStaticText[@name="{}"]'
    LIST_UPCOMING = '//XCUIElementTypeStaticText[@name="Upcoming"]'
    LIST_FINISHED = '//XCUIElementTypeStaticText[@name="Finished"]'
    LIST_EXPIRED = '//XCUIElementTypeStaticText[@name="Expired"]'
    TAB_HOME = '//XCUIElementTypeButton[starts-with(@name,"Home")]'
    TAB_ACTIVITY = '//XCUIElementTypeButton[starts-with(@name,"Activity")]'
    TAB_ACCOUNT = '//XCUIElementTypeButton[starts-with(@name,"Account")]'
    LIST_BOOKINGS_SCROLL = '(//XCUIElementTypeScrollView)[2]'
