class TeeTimeBookingSummaryLocators:
    EL_HEADER = '//XCUIElementTypeOther[@name="Booking summary"]'
    BTN_BACK = '//XCUIElementTypeOther[@name="Booking summary"]/preceding-sibling::XCUIElementTypeButton[1]'
    TXT_VENUE_NAME = '//XCUIElementTypeStaticText[@name="{}"]'
    TXT_VALUE_BY_LABEL = '//XCUIElementTypeStaticText[@name="{}"]/following-sibling::XCUIElementTypeStaticText[1]'
    TXT_LABEL_DATE = '//XCUIElementTypeStaticText[@name="Date"]'
    TXT_LABEL_SESSION = '//XCUIElementTypeStaticText[@name="Session"]'
    TXT_LABEL_PREFERRED_TIME = '//XCUIElementTypeStaticText[@name="Preferred time"]'
    TXT_BOOKING_TYPE = '//XCUIElementTypeStaticText[@name="Standard booking"]'
    IMG_PLAYER_BY_NAME = '//XCUIElementTypeImage[contains(@name,"{}") and not(contains(@name,"Published rate"))]'
    LIST_PLAYERS = '//XCUIElementTypeImage[contains(@name,"Swing Pass member") or contains(@name,"Regular Swing player")]'
    TXT_PUBLISHED_RATE = '//XCUIElementTypeStaticText[starts-with(@name,"Published rate")]'
    TXT_PROMO_LINE_BY_NAME = '//XCUIElementTypeStaticText[starts-with(@name,"{}")]'
    TXT_NOTES_TITLE = '//XCUIElementTypeStaticText[starts-with(@name,"Notes to")]'
    TXT_NOTES_VALUE = '//XCUIElementTypeStaticText[contains(@name,"reservation notes")]'
    TXT_TERMS_TITLE = '//XCUIElementTypeStaticText[@name="Terms & conditions"]'
    BTN_SHOW_MORE = '//XCUIElementTypeButton[@name="Show more"]'
    TXT_PRICE_DETAILS_TITLE = '//XCUIElementTypeStaticText[@name="Price details"]'
    IMG_PRICE_LINE_BY_PLAYER = '//XCUIElementTypeImage[starts-with(@name,"{}") and contains(@name,"Published rate")]'
    EL_PROCESSING_FEE = '//XCUIElementTypeOther[starts-with(@name,"Processing fee")]'
    TXT_TOTAL_PAYMENT = '//XCUIElementTypeStaticText[starts-with(@name,"Total payment")]'
