class TeeTimeBookingSuccessLocators:
    TXT_TITLE = '//XCUIElementTypeStaticText[@name="You’re confirmed!"]'
    TXT_SUBTITLE = '//XCUIElementTypeStaticText[@name="See you on the golf course"]'
    IMG_SUCCESS = '(//XCUIElementTypeScrollView)[1]/following-sibling::XCUIElementTypeImage[1]'
    EL_SWING_PASS_BANNER = '//XCUIElementTypeOther[contains(@name,"joining Swing Pass")]'
    TXT_VENUE_NAME = '//XCUIElementTypeStaticText[@name="{}"]'
    TXT_VENUE = '//XCUIElementTypeStaticText[starts-with(@name,"Booking #")]/preceding-sibling::XCUIElementTypeStaticText[1]'
    TXT_BOOKING_CODE = '//XCUIElementTypeStaticText[starts-with(@name,"Booking #")]'
    TXT_VALUE_BY_LABEL = '//XCUIElementTypeStaticText[@name="{}"]/following-sibling::XCUIElementTypeStaticText[1]'
    TXT_LABEL_DATE = '//XCUIElementTypeStaticText[@name="Date"]'
    TXT_LABEL_SESSION = '//XCUIElementTypeStaticText[@name="Session"]'
    TXT_LABEL_PREFERRED_TEE_TIME = '//XCUIElementTypeStaticText[@name="Preferred tee time"]'
    TXT_LABEL_PLAYERS = '//XCUIElementTypeStaticText[@name="No. of players"]'
    TXT_LABEL_TOTAL = '//XCUIElementTypeStaticText[@name="Total"]'
    TXT_LABEL_PAYMENT_METHOD = '//XCUIElementTypeStaticText[@name="Payment method"]'
    IMG_PAYMENT_METHOD = '//XCUIElementTypeStaticText[@name="Payment method"]/following-sibling::XCUIElementTypeImage[1]'
    TXT_EARNED_CREDITS_LABEL = '//XCUIElementTypeStaticText[@name="Swing Credits you earned"]'
    EL_EARNED_CREDITS = '//XCUIElementTypeOther[starts-with(@name,"+ ")]'
    TXT_CREDITS_NOTE = '//XCUIElementTypeStaticText[starts-with(@name,"Swing Credits will only be issued")]'
    BTN_FINISH = '//XCUIElementTypeButton[@name="Finish"]'
    BTN_SEE_BOOKING_DETAILS = '//XCUIElementTypeButton[@name="See booking details"]'
