class GolfCourseDetailsLocators:
    EL_HEADER = '//XCUIElementTypeOther[@name="Golf course details"]'
    BTN_BACK = '//XCUIElementTypeOther[@name="Golf course details"]/preceding-sibling::XCUIElementTypeButton[1]'
    BTN_SHARE = '//XCUIElementTypeOther[@name="Golf course details"]/following-sibling::XCUIElementTypeButton[1]'
    IMG_HERO = '((//XCUIElementTypeScrollView)[1]/following-sibling::XCUIElementTypeOther[1]//XCUIElementTypeImage)[1]'
    TXT_VENUE_NAME = '//XCUIElementTypeStaticText[@name="{}"]'
    TXT_LOCATION = '//XCUIElementTypeStaticText[@name="{}"]'
    TXT_VENUE_LOCATION = '//XCUIElementTypeStaticText[@name="\u2022"]/preceding-sibling::XCUIElementTypeStaticText[1]'
    TXT_DISTANCE = '//XCUIElementTypeStaticText[contains(@name,"km away")]'
    IMG_PROMO_BY_NAME = '//XCUIElementTypeImage[starts-with(@name,"{}")]'
    LIST_PROMOS = '//XCUIElementTypeImage[contains(@name,"Valid until")]'
    EL_PROMO_STRIP = '//XCUIElementTypeButton[@name="See all"]/preceding-sibling::XCUIElementTypeOther[1]'
    BTN_SEE_ALL_PROMOS = '//XCUIElementTypeButton[@name="See all"]'
    EL_CASHBACK_BANNER = '//XCUIElementTypeOther[starts-with(@name,"Earn up to")]'
    BTN_CALENDAR = '//XCUIElementTypeOther[XCUIElementTypeOther[starts-with(@name,"Earn up to")]]/following-sibling::XCUIElementTypeImage[1]'
    TXT_DATE_BY_LABEL = '//XCUIElementTypeStaticText[@name="{}"]'
    TXT_DATE_BY_DAY = '//XCUIElementTypeStaticText[starts-with(@name,"{}")]'
    LIST_DATE_STRIP = '//XCUIElementTypeScrollView/following-sibling::XCUIElementTypeStaticText[contains(@name,"\n")]'
    EL_DATE_STRIP = '//XCUIElementTypeOther[XCUIElementTypeScrollView and XCUIElementTypeStaticText[contains(@name,"\n")]]/XCUIElementTypeScrollView'
    IMG_SESSION_TAB_BY_NAME = '//XCUIElementTypeImage[starts-with(@name,"{}")]'
    LIST_SESSION_TABS = '//XCUIElementTypeImage[contains(@name,"Session") and contains(@name,"Tab")]'
    IMG_SESSION_TAB_SELECTED = '//XCUIElementTypeImage[contains(@name,"Session") and contains(@traits,"Selected")]'
    IMG_DAY_SESSION_TAB = '//XCUIElementTypeImage[starts-with(@name,"Day Session")]'
    IMG_NIGHT_SESSION_TAB = '//XCUIElementTypeImage[starts-with(@name,"Night Session")]'
    TXT_SELECT_TEE_TIME = '//XCUIElementTypeStaticText[@name="Select preferred tee time"]'
    IMG_TEE_TIME_TOGGLE = '//XCUIElementTypeStaticText[@name="Select preferred tee time"]/following-sibling::XCUIElementTypeImage[1]'
    EL_SLOT_BY_TIME = '//XCUIElementTypeOther[starts-with(@name,"{}")]'
    LIST_SLOTS = '//XCUIElementTypeOther[contains(@name," / pax")]'
    LIST_UNAVAILABLE_SLOTS = '//XCUIElementTypeOther[contains(@name,"Unavailable")]'
    TXT_DISCOUNT_BY_SLOT = '//XCUIElementTypeOther[starts-with(@name,"{}")]/following-sibling::XCUIElementTypeStaticText[1]'
    LIST_SLOT_DISCOUNTS = '//XCUIElementTypeStaticText[starts-with(@name,"-") and contains(@name,"%")]'
    TXT_PRICES_INCLUDE = '//XCUIElementTypeStaticText[@name="Prices shown include:"]'
    EL_INCLUSION_BY_NAME = '//XCUIElementTypeOther[@name="{}"]'
    IMG_CASHBACK_BADGE = '//XCUIElementTypeImage[contains(@name,"Cashback")]'
    BTN_BOOK_TEE_TIME = '//XCUIElementTypeButton[@name="Book tee time"]'
    TXT_LOCATION_TITLE = '//XCUIElementTypeStaticText[@name="Location"]'
    TXT_DISTANCE_FROM_LOCATION = '//XCUIElementTypeStaticText[contains(@name,"from your location")]'
    TXT_ADDRESS_BY_TEXT = '//XCUIElementTypeStaticText[contains(@name,"{}")]'
    BTN_VIEW_ON_MAPS = '//XCUIElementTypeButton[@name="View on Google Maps"]'
    TXT_MORE_INFORMATION = '//XCUIElementTypeStaticText[@name="More information"]'
    BTN_SHOW_MORE = '//XCUIElementTypeButton[@name="Show more"]'
    TXT_SPEC_BY_LABEL = '//XCUIElementTypeStaticText[starts-with(@name,"{}")]'
    IMG_FACILITY_BY_NAME = '//XCUIElementTypeImage[@name="{}"]'
    
    BTN_PROMO_ACTIVE = '//XCUIElementTypeButton[@name="Active"]'
    BTN_PROMO_JOIN = '//XCUIElementTypeButton[@name="Join"]'
    BTN_PROMO_RENEW = '//XCUIElementTypeButton[@name="Renew"]'
