class TeeTimeBookingDetailsLocators:
    EL_HEADER = '//XCUIElementTypeOther[@name="Booking details"]'
    BTN_BACK = '//XCUIElementTypeOther[@name="Booking details"]/preceding-sibling::XCUIElementTypeButton[1]'
    BTN_MORE = '//XCUIElementTypeOther[@name="Booking details"]/following-sibling::XCUIElementTypeButton[1]'
    TXT_SUMMARY_TITLE = '//XCUIElementTypeStaticText[@name="Booking summary"]'
    TXT_STATUS = '//XCUIElementTypeStaticText[@name="UPCOMING"]'
    TXT_STATUS_BY_NAME = '//XCUIElementTypeStaticText[@name="{}"]'
    TXT_BOOKING_CODE = '//XCUIElementTypeStaticText[starts-with(@name,"Booking #")]'
    TXT_VALUE_BY_LABEL = '//XCUIElementTypeStaticText[@name="{}"]/following-sibling::XCUIElementTypeStaticText[1]'
    TXT_LABEL_DATE = '//XCUIElementTypeStaticText[@name="Date"]'
    TXT_LABEL_SESSION = '//XCUIElementTypeStaticText[@name="Session"]'
    TXT_LABEL_PREFERRED_TIME = '//XCUIElementTypeStaticText[@name="Preferred time"]'
    TXT_LABEL_PLAYERS = '//XCUIElementTypeStaticText[@name="No. of players"]'
    BTN_SEE_BREAKDOWN = '//XCUIElementTypeButton[@name="See complete breakdown"]'
    TXT_PAYMENT_SUMMARY_TITLE = '//XCUIElementTypeStaticText[@name="Payment summary"]'
    TXT_SUBTOTAL = '//XCUIElementTypeStaticText[starts-with(@name,"Subtotal")]'
    EL_PROCESSING_FEE = '//XCUIElementTypeOther[starts-with(@name,"Processing fee")]'
    IMG_TOTAL_PAYMENT = '//XCUIElementTypeImage[starts-with(@name,"Total payment")]'
    TXT_EARNED_CREDITS_LABEL = '//XCUIElementTypeStaticText[@name="Swing Credits you earned"]'
    EL_EARNED_CREDITS = '//XCUIElementTypeOther[starts-with(@name,"+")]'
    TXT_CREDITS_NOTE = '//XCUIElementTypeStaticText[starts-with(@name,"Swing Credits will only be issued")]'
    BTN_SEE_RECEIPT = '//XCUIElementTypeButton[@name="See receipt"]'
    TXT_HISTORY_TITLE = '//XCUIElementTypeStaticText[@name="History"]'
    IMG_HISTORY_ITEM_BY_NAME = '//XCUIElementTypeImage[starts-with(@name,"{}")]'
    LIST_HISTORY_ITEMS = '//XCUIElementTypeStaticText[@name="History"]/following-sibling::XCUIElementTypeOther//XCUIElementTypeImage'
