class CompleteProfileLocators:
    TXT_WELCOME = '//XCUIElementTypeStaticText[@name="Hi, welcome to Swing! Let\'s begin by setting up your account and profile."]'
    INPUT_FIRST_NAME = '//XCUIElementTypeTextField[@name="First name"]'
    INPUT_LAST_NAME = '//XCUIElementTypeTextField[@name="Last name"]'
    INPUT_USERNAME = '//XCUIElementTypeTextField[@name="Username"]'
    INPUT_EMAIL = '//XCUIElementTypeTextField[@name="Email"]'
    INPUT_REFERRAL_CODE = '//XCUIElementTypeTextField[@name="Referral code"]'
    EL_BIRTHDAY = '//XCUIElementTypeOther[@name="Birthday"]'
    EL_NATIONALITY = '//XCUIElementTypeOther[@name="Nationality"]'
    EL_GENDER = '//XCUIElementTypeOther[@name="Gender"]'
    EL_FIELD_BY_NAME = '//XCUIElementTypeOther[@name="{}"]'
    BTN_BIRTHDAY = '//XCUIElementTypeOther[XCUIElementTypeOther[@name="Birthday"]]/XCUIElementTypeButton'
    BTN_NATIONALITY = '//XCUIElementTypeOther[XCUIElementTypeOther[@name="Nationality"]]/XCUIElementTypeButton'
    BTN_GENDER = '//XCUIElementTypeOther[XCUIElementTypeOther[@name="Gender"]]/XCUIElementTypeButton'
    BTN_FIELD_BY_NAME = '//XCUIElementTypeOther[XCUIElementTypeOther[@name="{}"]]/XCUIElementTypeButton'
    TXT_USERNAME_HINT = '//XCUIElementTypeStaticText[@name="Your friends will be able to search for your profile and invite you when booking for a tee time."]'
    TXT_EMAIL_HINT = '//XCUIElementTypeStaticText[@name="We\'ll send your confirmations & receipts to this email"]'
    BTN_NEXT = '//XCUIElementTypeButton[@name="Next"]'
