class CreditsHistoryLocators:
    EL_HEADER = '//XCUIElementTypeOther[@name="Swing Credits history"]'
    BTN_BACK = '//XCUIElementTypeOther[@name="Swing Credits history"]/preceding-sibling::XCUIElementTypeButton[1]'
    TXT_TAB_BY_NAME = '//XCUIElementTypeStaticText[@name="{}"]'
    TXT_TAB_ALL = '//XCUIElementTypeStaticText[@name="All"]'
    TXT_TAB_EARNED = '//XCUIElementTypeStaticText[@name="Credits Earned"]'
    TXT_TAB_USAGE = '//XCUIElementTypeStaticText[@name="Credits Usage"]'
    LIST_DATE_GROUPS = '//XCUIElementTypeOther[contains(@name,", ") and contains(@name," 20")]'
    EL_DATE_GROUP_BY_LABEL = '//XCUIElementTypeOther[@name="{}"]'
    LIST_ITEMS = '//XCUIElementTypeOther[contains(@name,"swing_credit_history_item_")] | //XCUIElementTypeImage[contains(@name,"swing_credit_history_item_")]'
    EL_ITEM_BY_BOOKING_CODE = '//XCUIElementTypeOther[contains(@name,"swing_credit_history_item_") and contains(@label,"#{0}")] | //XCUIElementTypeImage[contains(@name,"swing_credit_history_item_") and contains(@label,"#{0}")]'
    LIST_EARNED_ITEMS = '//XCUIElementTypeOther[contains(@name,"swing_credit_history_item_") and contains(@label,"earned")] | //XCUIElementTypeImage[contains(@name,"swing_credit_history_item_") and contains(@label,"earned")]'
    LIST_USED_ITEMS = '//XCUIElementTypeOther[contains(@name,"swing_credit_history_item_") and contains(@label,"used")] | //XCUIElementTypeImage[contains(@name,"swing_credit_history_item_") and contains(@label,"used")]'
    LIST_ITEMS_BY_BOOKING_TYPE = '//XCUIElementTypeOther[contains(@name,"swing_credit_history_item_") and starts-with(@label,"{0}")] | //XCUIElementTypeImage[contains(@name,"swing_credit_history_item_") and starts-with(@label,"{0}")]'
    LIST_ITEM_BY_BOOKING_CODE = '//XCUIElementTypeOther[contains(@label, "{}")]'
