class SwingCreditsLocators:
    EL_HEADER = '//XCUIElementTypeOther[@name="Swing Credits"]'
    BTN_BACK = '//XCUIElementTypeOther[@name="Swing Credits"]/preceding-sibling::XCUIElementTypeButton[1]'
    IMG_COUNTRY = '//XCUIElementTypeImage[@name="ID"]'
    TXT_BALANCE = '//XCUIElementTypeStaticText[@name="swing_credits_balance_text"]'
    EL_REDEEM = '//XCUIElementTypeOther[@name="swing_credits_redeem_button"]'
    BTN_REDEEM = '//XCUIElementTypeOther[@name="swing_credits_redeem_button"]/following-sibling::XCUIElementTypeButton[1]'
    EL_SCAN_TO_EARN = '//XCUIElementTypeOther[@name="swing_credits_scan_to_earn_button"]'
    BTN_SCAN_TO_EARN = '//XCUIElementTypeOther[@name="swing_credits_scan_to_earn_button"]/following-sibling::XCUIElementTypeButton[1]'
    EL_AUTO_APPLY = '//XCUIElementTypeOther[@name="swing_credits_auto_apply_toggle"]'
    SWITCH_AUTO_APPLY = '//XCUIElementTypeOther[@name="swing_credits_auto_apply_toggle"]/following-sibling::XCUIElementTypeSwitch[1]'
    EL_SEE_ALL_CASHBACKS = '//XCUIElementTypeOther[@name="swing_credits_see_all_cashbacks_button"]'
    BTN_SEE_ALL_CASHBACKS = '//XCUIElementTypeOther[@name="swing_credits_see_all_cashbacks_button"]/following-sibling::XCUIElementTypeButton[1]'
    EL_LEARN_MORE = '//XCUIElementTypeOther[@name="swing_credits_learn_more_button"]'
    BTN_LEARN_MORE = '//XCUIElementTypeOther[@name="swing_credits_learn_more_button"]/following-sibling::XCUIElementTypeButton[1]'
    EL_SEE_HISTORY = '//XCUIElementTypeOther[@name="swing_credits_see_history_button"]'
    BTN_SEE_HISTORY = '//XCUIElementTypeOther[@name="swing_credits_see_history_button"]/following-sibling::XCUIElementTypeButton[1]'
    TXT_REWARDS_BANNER = '//XCUIElementTypeStaticText[@name="Redeem your Swing Credits for rewards!"]'
    LIST_REWARDS = '//XCUIElementTypeOther[contains(@name,"swing_credits_reward_item_")]'
    EL_REWARD_BY_TITLE = '//XCUIElementTypeOther[contains(@name,"swing_credits_reward_item_") and contains(@label,"{}")]'
    BTN_CATEGORY_ALL = '//XCUIElementTypeButton[@name="reward_category_chip_all"]'
    LIST_CATEGORY_CHIPS = '//XCUIElementTypeButton[contains(@name,"reward_category_chip_")]'
    TXT_CATEGORY_BY_NAME = '//XCUIElementTypeStaticText[@name="{}"]'
    EL_REWARD_SEARCH = '//XCUIElementTypeOther[@name="reward_search_field"]'
    INPUT_REWARD_SEARCH = '//XCUIElementTypeOther[@name="reward_search_field"]/following-sibling::XCUIElementTypeTextField'
