class BookingSuccessLocators:
    TXT_TITLE = '//XCUIElementTypeStaticText[@name="You’re confirmed!"]'
    TXT_SUBTITLE = '//XCUIElementTypeStaticText[@name="See you on the driving range"]'
    TXT_VENUE_NAME = '//XCUIElementTypeStaticText[@name="{}"]'
    TXT_BOOKING_CODE = '//XCUIElementTypeStaticText[starts-with(@name,"Booking #")]'
    TXT_VALUE_BY_LABEL = '//XCUIElementTypeStaticText[@name="{}"]/following-sibling::XCUIElementTypeStaticText[1]'
    TXT_LABEL_PLAYER_NAME = '//XCUIElementTypeStaticText[@name="Player name"]'
    TXT_LABEL_DATE = '//XCUIElementTypeStaticText[@name="Date"]'
    TXT_LABEL_BOOKING_TIME = '//XCUIElementTypeStaticText[@name="Booking time"]'
    TXT_LABEL_DURATION = '//XCUIElementTypeStaticText[@name="Duration"]'
    TXT_LABEL_BAYS = '//XCUIElementTypeStaticText[@name="Bays"]'
    TXT_LABEL_BAY_TYPE = '//XCUIElementTypeStaticText[@name="Bay type"]'
    TXT_LABEL_TOTAL = '//XCUIElementTypeStaticText[@name="Total"]'
    TXT_LABEL_PAYMENT_METHOD = '//XCUIElementTypeStaticText[@name="Payment method"]'
    TXT_EARNED_CREDITS_LABEL = '//XCUIElementTypeStaticText[@name="Swing Credits you earned"]'
    EL_EARNED_CREDITS = '//XCUIElementTypeOther[starts-with(@name,"+ ")]'
    TXT_CREDITS_NOTE = '//XCUIElementTypeStaticText[starts-with(@name,"Swing Credits will only be issued")]'
    BTN_FINISH = '//XCUIElementTypeButton[@name="Finish"]'
    BTN_SEE_BOOKING_DETAILS = '//XCUIElementTypeButton[@name="See booking details"]'
