class DrBookingDetailsLocators:
    EL_HEADER = '//XCUIElementTypeOther[@name="Booking details"]'
    BTN_BACK = '//XCUIElementTypeOther[@name="Booking details"]/preceding-sibling::XCUIElementTypeButton[1]'
    BTN_MORE = '//XCUIElementTypeOther[@name="Booking details"]/following-sibling::XCUIElementTypeButton[1]'
    TXT_SUMMARY_TITLE = '//XCUIElementTypeStaticText[@name="Booking summary"]'
    TXT_STATUS = '//XCUIElementTypeStaticText[@name="UPCOMING"]'
    TXT_STATUS_BY_NAME = '//XCUIElementTypeStaticText[@name="{}"]'
    TXT_BOOKING_CODE = '//XCUIElementTypeStaticText[starts-with(@name,"Booking #")]'
    TXT_VALUE_BY_LABEL = '//XCUIElementTypeStaticText[@name="{}"]/following-sibling::XCUIElementTypeStaticText[1]'
    TXT_LABEL_PLAYER_NAME = '//XCUIElementTypeStaticText[@name="Player name"]'
    TXT_LABEL_DATE = '//XCUIElementTypeStaticText[@name="Date"]'
    TXT_LABEL_BOOKING_TIME = '//XCUIElementTypeStaticText[@name="Booking time"]'
    TXT_LABEL_DURATION = '//XCUIElementTypeStaticText[@name="Duration"]'
    TXT_LABEL_NUMBER_OF_BAYS = '//XCUIElementTypeStaticText[@name="Number of bays"]'
    TXT_LABEL_BAY_TYPE = '//XCUIElementTypeStaticText[@name="Bay type"]'
    BTN_SEE_BREAKDOWN = '//XCUIElementTypeButton[@name="See complete breakdown"]'
    TXT_PAYMENT_SUMMARY_TITLE = '//XCUIElementTypeStaticText[@name="Payment summary"]'
    TXT_PRICE_LINE_BY_LABEL = '//XCUIElementTypeStaticText[starts-with(@name,"{}")]'
    TXT_SUBTOTAL = '//XCUIElementTypeStaticText[starts-with(@name,"Subtotal")]'
    EL_PROCESSING_FEE = '//XCUIElementTypeOther[starts-with(@name,"Processing fee")]'
    IMG_TOTAL_PAYMENT = '//XCUIElementTypeImage[starts-with(@name,"Total payment")]'
    TXT_EARNED_CREDITS_LABEL = '//XCUIElementTypeStaticText[@name="Swing Credits you earned"]'
    EL_EARNED_CREDITS = '//XCUIElementTypeOther[starts-with(@name,"+")]'
    BTN_SEE_RECEIPT = '//XCUIElementTypeButton[@name="See receipt"]'
    LBL_USED_CREDITS = '//XCUIElementTypeStaticText[starts-with(@name,"Swing Credits")]'
