class DrivingRangeDetailsLocators:
    EL_HEADER = '//XCUIElementTypeOther[@name="Driving range details"]'
    IMG_HERO = '((//XCUIElementTypeScrollView)[1]/following-sibling::XCUIElementTypeOther[1]//XCUIElementTypeImage)[1]'
    TXT_VENUE_NAME = '//XCUIElementTypeStaticText[@name="{}"]'
    TXT_LOCATION = '//XCUIElementTypeStaticText[@name="\u2022"]/preceding-sibling::XCUIElementTypeStaticText[1]'
    TXT_DISTANCE = '//XCUIElementTypeStaticText[@name="\u2022"]/following-sibling::XCUIElementTypeStaticText[1]'
    IMG_PROMO_BY_NAME = '//XCUIElementTypeImage[starts-with(@name,"{}")]'
    LIST_PROMOS = '//XCUIElementTypeImage[contains(@name,"Swing Pass Exclusive") or contains(@name,"Valid until")]'
    EL_PROMO_STRIP = '(//XCUIElementTypeOther[@name="Driving range details"]/parent::XCUIElementTypeOther/following-sibling::XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther//XCUIElementTypeScrollView)[1]'
    BTN_PROMO_ACTIVE = '//XCUIElementTypeButton[@name="Active"]'
    BTN_PROMO_JOIN = '//XCUIElementTypeButton[@name="Join"]'
    BTN_PROMO_RENEW = '//XCUIElementTypeButton[@name="Renew"]'
    BTN_SEE_ALL_PROMOS = '//XCUIElementTypeButton[@name="See all"]'
    EL_CASHBACK_BANNER = '//XCUIElementTypeOther[starts-with(@name,"Earn up to")]'
    BTN_CALENDAR = '//XCUIElementTypeStaticText[@name="Select time & duration"]/preceding-sibling::XCUIElementTypeImage[1]'
    TXT_DATE_BY_LABEL = '//XCUIElementTypeStaticText[@name="{}"]'
    LIST_DATE_STRIP = '//XCUIElementTypeScrollView/following-sibling::XCUIElementTypeStaticText[contains(@name,"\n")]'
    EL_DATE_STRIP = '//XCUIElementTypeOther[XCUIElementTypeScrollView and XCUIElementTypeStaticText[contains(@name,"\n")]]/XCUIElementTypeScrollView'
    EL_TAB_BAY_TYPE = '//*[contains(@name,"{}")]'
    TXT_SELECT_TIME_TITLE = '//XCUIElementTypeStaticText[@name="Select time & duration"]'
    TXT_TIME_SLOT = '//XCUIElementTypeStaticText[@name="{}"]'
    LIST_TIME_SLOTS = '//XCUIElementTypeStaticText[string-length(@name)=5 and contains(@name,":")]'
    TXT_DURATION_TITLE = '//XCUIElementTypeStaticText[@name="Duration"]'
    TXT_DURATION_OPTION = '//XCUIElementTypeStaticText[@name="{}"]'
    LIST_DURATIONS = '//XCUIElementTypeStaticText[contains(@name," min")]'
    EL_DURATION_STRIP = '//XCUIElementTypeStaticText[@name="Duration"]/following-sibling::XCUIElementTypeOther[1]//XCUIElementTypeScrollView'
    TXT_RATES_TITLE = '//XCUIElementTypeStaticText[starts-with(@name,"Rates & prices")]'
    IMG_RATE_BY_DURATION = '//XCUIElementTypeImage[starts-with(@name,"{}")]'
    BTN_SEE_PRICELIST = '//XCUIElementTypeButton[@name="See complete pricelist"]'
    TXT_LOCATION_TITLE = '//XCUIElementTypeStaticText[@name="Location"]'
    TXT_ADDRESS = '//XCUIElementTypeStaticText[@name="Location"]/following-sibling::XCUIElementTypeStaticText[1]'
    TXT_DISTANCE_FROM_LOCATION = '//XCUIElementTypeStaticText[contains(@name,"from your location")]'
    EL_MAP = '//XCUIElementTypeOther[starts-with(@name,"staticmap")]'
    BTN_GOOGLE_MAPS = '//XCUIElementTypeButton[@name="View on Google Maps"]'
    TXT_MORE_INFORMATION = '//XCUIElementTypeStaticText[@name="More Information"]'
    TXT_DESCRIPTION = '//XCUIElementTypeStaticText[@name="More Information"]/following-sibling::XCUIElementTypeStaticText[1]'
    BTN_SHOW_MORE = '//XCUIElementTypeButton[@name="Show more"]'
    BTN_BOOK = '//XCUIElementTypeButton[@name="Book driving range"]'
    BTN_BACK = '//XCUIElementTypeOther[@name="Driving range details"]/preceding-sibling::XCUIElementTypeButton[1]'
    BTN_SHARE = '//XCUIElementTypeOther[@name="Driving range details"]/following-sibling::XCUIElementTypeButton[1]'
